# Generated by Django 2.2 on 2019-12-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191210_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', 'updated', 'timestamp']},
        ),
    ]
