# Generated by Django 2.2.8 on 2020-02-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191211_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date', '-updated', '-timestamp'], 'permissions': (('view_blog', 'Can view the blog'), ('can_publish_blog', 'Can publish a blog'))},
        ),
    ]
